# Generated by Django 5.2.3 on 2025-06-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse_contextuelle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PESTEL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Politique', 'Politique'), ('Économique', 'Économique'), ('Sociologique', 'Sociologique'), ('Technologique', 'Technologique'), ('Environnemental', 'Environnemental'), ('Légal', 'Légal')], max_length=20)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
